### ISSUE TITLE
STORE: ADD PRODUCT - Submission when not tracking by options

### ISSUE THREAD

**Issue by DENICHOLS** [timeforcamp/time-for-camp#98] opened 2020-02-13 17:21 UTC
When you add a new product where **TRACK INVENTORY** is set to **YES**, but **Tracking By Options** is set to **NO**, the submit action should take you back to the products table instead of keeping you in the product details page.

**Comment by timeforcamp** [comment] 2020-02-15 14:39
duplicate of #100

**Closed as completed** 2020-02-15 14:39 UTC
Labels: duplicate, ui modification
